services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true

parameters:

  austral.admin.class.graphic_items.item.class:                                     Austral\GraphicItemsBundle\Admin\ItemAdmin
  austral.admin.class.graphic_items.item_category.class:                            Austral\GraphicItemsBundle\Admin\ItemCategoryAdmin

  austral.admin.modules.graphic_items_bundle.config.enabled:                        true
  austral.admin.modules.graphic_items_bundle.config.item.enabled:                   true
  austral.admin.modules.graphic_items_bundle.config.item_category.enabled:          true

  austral_admin.modules.graphic_items_bundle:
    config_graphic_items:
      enabled:                    "%austral.admin.modules.graphic_items_bundle.config.enabled%"
      navigation:
        position:                 500
      name:                       "Configuration"
      picto:                      "austral-picto-cog"
      route:                      "config"
      translate:                  "female_c"
      actions:
        index:                    "listChildrenModules"
      children:
        item_category:
          enabled:                "%austral.admin.modules.graphic_items_bundle.config.item_category.enabled%"
          name:                   "Graphic Items Category"
          picto:                  "austral-picto-activity"
          pictoTile:              "parameters"
          route:                  "graphic-item-category"
          entity_manager:         "austral.entity_manager.graphic_items.item_category"
          class:                  "%austral.admin.class.graphic_items.item_category.class%"
          translate:              "male_c"
          sortable:               true
        item:
          enabled:                "%austral.admin.modules.graphic_items_bundle.config.item.enabled%"
          name:                   "Graphic Items"
          picto:                  "austral-picto-activity"
          pictoTile:              "parameters"
          route:                  "graphic-item"
          entity_manager:         "austral.entity_manager.graphic_items.item"
          class:                  "%austral.admin.class.graphic_items.item.class%"
          translate:              "male_c"
