services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true

  austral.graphic_items.management:
    class:          Austral\GraphicItemsBundle\Services\GraphicItemManagement
    arguments:      ["@austral.graphic_items.simple_icon", "@austral.graphic_items.austral_picto", "@austral.graphic_items.custom_picto"]

  austral.graphic_items.simple_icon:
    class:          Austral\GraphicItemsBundle\Services\SimpleIcon
    arguments:      ["@service_container"]

  austral.graphic_items.austral_picto:
    class:          Austral\GraphicItemsBundle\Services\AustralPicto
    arguments:      ["@service_container"]

  austral.graphic_items.custom_picto:
    class:          Austral\GraphicItemsBundle\Services\CustomPicto
    arguments:      ["@service_container"]


##### Twig Extension detected
  twig.extension.graphic_items:
    class:        Austral\GraphicItemsBundle\TwigExtension\GraphicItemTwig
    arguments:    ['@austral.graphic_items.management', "@router"]
    tags:
      - { name: twig.extension }

##### Entities Manager #####

  ##### Config Entity Manager
  austral.entity_manager.graphic_items.item:
    class:          Austral\GraphicItemsBundle\EntityManager\ItemEntityManager
    arguments:      [ "@doctrine.orm.entity_manager",  "@event_dispatcher", "%austral.entity.graphic_items.item.class%" ]

  austral.entity_manager.graphic_items.item_category:
    class:          Austral\GraphicItemsBundle\EntityManager\ItemCategoryEntityManager
    arguments:      [ "@doctrine.orm.entity_manager",  "@event_dispatcher", "%austral.entity.graphic_items.item_category.class%" ]
